CREATE TABLE IF NOT EXISTS `Users` (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Campground (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  loc_id INTEGER NOT NULL,
  owner_id INTEGER NOT NULL,
  FOREIGN KEY(owner_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(loc_id) REFERENCES Location(id) ON DELETE SET NULL 
);