USE campground;

CREATE TABLE IF NOT EXISTS Users(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Location (
  id INTEGER AUTO_INCREMENT PRIMARY KEY, 
  place VARCHAR(64) NOT NULL,
  longitude NUMERIC(9,6) NOT NULL CHECK(longitude BETWEEN -180 AND 180),
  latitude NUMERIC(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  UNIQUE (longitude,latitude)
);

CREATE TABLE IF NOT EXISTS Campground (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  loc_id INTEGER,
  owner_id INTEGER NOT NULL,
  FOREIGN KEY(owner_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(loc_id) REFERENCES Location(id) ON DELETE SET NULL 
);

CREATE TABLE IF NOT EXISTS Facility (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS Review (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  campground_id INTEGER NOT NULL,
  content VARCHAR(1024),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  FOREIGN KEY(user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(campground_id) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Booking (
  user_id INTEGER NOT NULL,
  campground_id INTEGER NOT NULL,
  date DATE,
  price NUMERIC NOT NULL,
  PRIMARY KEY(user_id,campground_id,dat),
  FOREIGN KEY(user_id) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(campground_id) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HasFacility(
  facility_id INTEGER,
  campground_id INTEGER,
  PRIMARY KEY(facility_id,campground_id),
  FOREIGN KEY(facility_id) REFERENCES Facility(id) ON DELETE CASCADE,
  FOREIGN KEY(campground_id) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HasFavourite(
  user_id INTEGER,
  campground_id INTEGER,
  PRIMARY KEY(campground_id,user_id),
  FOREIGN KEY(campground_id) REFERENCES Campground(id),
  FOREIGN KEY(user_id) REFERENCES Users(id) 
);

CREATE TABLE IF NOT EXISTS Images(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  img_url VARCHAR(1024) NOT NULL,
  campground_id INTEGER,
  FOREIGN KEY(campground_id) REFERENCES Campground(id)
);
