CREATE DATABASE IF NOT EXISTS campgrounds_db;

USE campgrounds_db;

CREATE TABLE IF NOT EXISTS Users(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL,
  role ENUM('admin','user') DEFAULT 'user',
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Location (
  id INTEGER AUTO_INCREMENT PRIMARY KEY, 
  place VARCHAR(64) NOT NULL,
  longitude NUMERIC(9,6) NOT NULL CHECK(longitude BETWEEN -180 AND 180),
  latitude NUMERIC(9,6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  UNIQUE (longitude,latitude)
);

CREATE TABLE IF NOT EXISTS Campground (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(64) NOT NULL,
  description VARCHAR(4096),
  capacity INTEGER NOT NULL,
  type VARCHAR(64),
  locId INTEGER,
  ownerId INTEGER NOT NULL,
  isApproved BOOLEAN DEFAULT FALSE NOT NULL,
  price NUMERIC NOT NULL,
  FOREIGN KEY(ownerId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(locId) REFERENCES Location(id) ON DELETE SET NULL 
);

CREATE TABLE IF NOT EXISTS Request(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  requestedBy INTEGER NOT NULL,
  campgroundId INTEGER NOT NULL,
  status ENUM('approved','rejected','pending') DEFAULT 'pending',
  FOREIGN KEY(requestedBy) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Amenity (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) UNIQUE NOT NULL,
  isPaid BOOLEAN DEFAULT FALSE,
  price NUMERIC DEFAULT 0.0 
);

CREATE TABLE IF NOT EXISTS Review (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  userId INTEGER NOT NULL,
  campgroundId INTEGER NOT NULL,
  content VARCHAR(1024),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  FOREIGN KEY(userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Booking (
  userId INTEGER NOT NULL,
  bookingId INTEGER AUTO_INCREMENT UNIQUE NOT NULL,
  campgroundId INTEGER NOT NULL,
  checkInDate DATE,
  checkOutDate DATE,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  amount NUMERIC NOT NULL,
  PRIMARY KEY(userId,campgroundId,checkInDate),
  FOREIGN KEY(userId) REFERENCES Users(id) ON DELETE CASCADE,
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE,
  CONSTRAINT check_date CHECK(checkInDate < checkOutDate)
);

CREATE TABLE IF NOT EXISTS HasAmenity(
  amenity_id INTEGER,
  campgroundId INTEGER,
  PRIMARY KEY(amenity_id,campgroundId),
  FOREIGN KEY(amenity_id) REFERENCES Amenity(id) ON DELETE CASCADE,
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS HasFavourite(
  userId INTEGER,
  campgroundId INTEGER,
  PRIMARY KEY(campgroundId,userId),
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE,
  FOREIGN KEY(userId) REFERENCES Users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Images(
  id INTEGER,
  imgUrl VARCHAR(1024) NOT NULL,
  campgroundId INTEGER,
  PRIMARY KEY(id,campgroundId),
  FOREIGN KEY(campgroundId) REFERENCES Campground(id)
);

CREATE TABLE IF NOT EXISTS Notifications(
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  content VARCHAR(1024) NOT NULL,
  userId INTEGER NOT NULL,
  viewed BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS ApprovalNotif (
  notifId INTEGER PRIMARY KEY,
  requestId INTEGER NOT NULL,
  FOREIGN KEY(requestId) REFERENCES Request(id) ON DELETE CASCADE,
  FOREIGN KEY(notifId) REFERENCES Notifications(id) ON DELETE CASCADE  
);

CREATE TABLE IF NOT EXISTS BookingNotif (
  notifId INTEGER PRIMARY KEY,
  bookingId INTEGER,
  FOREIGN KEY(bookingId) REFERENCES Booking(bookingId) ON DELETE CASCADE,
  FOREIGN KEY(notifId) REFERENCES Notifications(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FAQs(
  faqId INTEGER AUTO_INCREMENT PRIMARY KEY,
  question VARCHAR(1024) NOT NULL,
  answer VARCHAR(2048) NOT NULL
);

CREATE TABLE IF NOT EXISTS Rules(
  campgroundId INTEGER NOT NULL,
  checkInStart TIME NOT NULL DEFAULT "14:00:00", 
  checkInEnd TIME NOT NULL DEFAULT "00:00:00",
  checkOutStart TIME NOT NULL DEFAULT "00:00:00",
  checkOutEnd TIME NOT NULL DEFAULT "12:00:00",
  cancellationPolicy VARCHAR(1024),
  cash BOOLEAN DEFAULT TRUE,
  upi BOOLEAN DEFAULT FALSE,
  card BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (campgroundId),
  FOREIGN KEY(campgroundId) REFERENCES Campground(id) ON DELETE CASCADE
);
